### ISSUE TITLE
Homebrew Tap seems to be broken

### ISSUE THREAD

**Issue by mgray88** [wtfutil/wtf#1264]
## What's broken?
```shell
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/wtfutil/homebrew-wtfutil/wtfutil.rb
wtfutil: wrong number of arguments (given 1, expected 0)
Error: Cannot tap wtfutil/wtfutil: invalid syntax in tap!
```

Edit to add (with the debug flag):
```shell
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/wtfutil/homebrew-wtfutil/wtfutil.rb
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/wtfutil/homebrew-wtfutil/wtfutil.rb
wtfutil: wrong number of arguments (given 1, expected 0)
Error: Cannot tap wtfutil/wtfutil: invalid syntax in tap!
/usr/local/Homebrew/Library/Homebrew/tap.rb:314:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/tap.rb:65:in `tap'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

**Comment by Seanstoppable** [comment]
There seems to be a maintained version in [homebrew core](https://github.com/Homebrew/homebrew-core/blob/master/Formula/wtfutil.rb). Should we spin down the seperate tap?

**Comment by FelicianoTech** [comment]
Related: https://github.com/wtfutil/wtf/issues/1726

**Comment by FelicianoTech** [comment]
This issue was opened several years ago. It hasn't had recent comments and the tap has gotten some updates recently. For those reasons, I'm going to close this issue. 

If there's further/new problems with the tap, please open a new issue.
