### ISSUE TITLE
Brew broken after `cleanup` on Catalina (Mac OS)

### ISSUE THREAD

**Issue by Krijger** [wtfutil/wtf#770]
## What's broken?

After `brew cleanup`, brew was broken (Ruby LoadError). I was able to fix it with a `brew update`. This issue is for

- reference in case other have the same issue, leading them to the `brew update` fix
- to let the developers know, in case this does give some interesting insight for people who know better than me what is going on here

``` lang=zsh
➜  ~ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: No developer tools installed.
Install the Command Line Tools:
  xcode-select --install


Warning: Broken symlinks were found. Remove them with `brew cleanup`:
  /usr/local/bin/docker-credential-osxkeychain.backup
  /usr/local/bin/hyperkit.backup
  /usr/local/bin/notary.backup
  /usr/local/bin/vpnkit.backup
➜  ~ brew cleanup
.
.
.
Pruned 4 symbolic links and 6 directories from /usr/local
➜  ~ brew doctor
Traceback (most recent call last):
	4: from /usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `<main>'
	3: from /usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `require_relative'
	2: from /usr/local/Homebrew/Library/Homebrew/global.rb:13:in `<top (required)>'
	1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- active_support/core_ext/object/blank (LoadError)
➜  ~ brew config
Traceback (most recent call last):
	4: from /usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `<main>'
	3: from /usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `require_relative'
	2: from /usr/local/Homebrew/Library/Homebrew/global.rb:13:in `<top (required)>'
	1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- active_support/core_ext/object/blank (LoadError)
➜  ~ brew update
To restore the stashed changes to /usr/local/Homebrew run:
  'cd /usr/local/Homebrew && git stash pop'
Updated 1 tap (homebrew/core).
==> New Formulae
pympress
==> Updated Formulae
bluepill      cash-cli      checkstyle    elm           eslint        gitleaks      mutt          rargs         singular      vips
➜  ~ brew config
HOMEBREW_VERSION: 2.2.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7d7de295dfbc5e581106e2b1f674496b5e25a773
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 43ad053e9c72b06e657c0aff07ecd96a1f2ebd22
Core tap last commit: 9 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: N/A
Git: 2.16.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_121
macOS: 10.15.1-x86_64
CLT: N/A
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
```

**Comment by senorprogrammer** [comment]
Thanks for the information!

**Comment by souzapd** [comment]
I have just experienced the same problem, but ```brew update``` did not solve the issue.

I used ```brew update-reset```, as indicated by SMillerDev on [Missing File - Homebrew Dead? @ Homebrew Community Discussion].

**Comment by souzapd** [comment]
I have just experienced the same problem, but brew update did not solve the issue.

I used brew update-reset, as indicated by SMillerDev on [Missing File - Homebrew Dead? @ Homebrew Community Discussion](https://discourse.brew.sh/t/missing-file-homebrew-dead/5657).

**Comment by rogerhu** [comment]
There is a fix https://github.com/Homebrew/brew/pull/6940 that should resolve this issue.  Hopefully the release will be out soon.  Brew update reset should fix the issue as a workaround.

**Comment by senorprogrammer** [comment]
I believe this is fixed in Homebrew now.
