### ISSUE TITLE
Docker Module Panic

### ISSUE THREAD

**Issue by PartyLich** [wtfutil/wtf#773]
## How can we help?
After adding the docker module to my config, I get a panic! and crash.
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x589cd7]

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1(0xc0005d4d00)
	/Users/ccummer/go/pkg/mod/github.com/rivo/tview@v0.0.0-20190829161255-f8bc69b90341/application.go:149 +0x82
panic(0x1b57d80, 0x317f7d0)
	/usr/local/Cellar/go/1.13.1/libexec/src/runtime/panic.go:679 +0x1b2
github.com/olebedev/config.(*Config).Bool(0x0, 0x1eba379, 0x18, 0x0, 0x1, 0xc000437c08)
	/Users/ccummer/go/pkg/mod/github.com/olebedev/config@v0.0.0-20190528211619-364964f3a8e4/config.go:147 +0x37
github.com/olebedev/config.(*Config).UBool(0x0, 0x1eba379, 0x18, 0xc000437c47, 0x1, 0x1, 0xc000437d14)
	/Users/ccummer/go/pkg/mod/github.com/olebedev/config@v0.0.0-20190528211619-364964f3a8e4/config.go:162 +0x3f
github.com/wtfutil/wtf/app.(*FocusTracker).useNavShortcuts(...)
	/Users/ccummer/go/src/github.com/wtfutil/wtf/app/focus_tracker.go:250
github.com/wtfutil/wtf/app.(*FocusTracker).FocusOn(0xc0004b44a8, 0x309a540, 0x1, 0x1)
	/Users/ccummer/go/src/github.com/wtfutil/wtf/app/focus_tracker.go:48 +0x6f
github.com/wtfutil/wtf/app.(*WtfApp).keyboardIntercept(0xc0004b4480, 0xc000bee020, 0xc0005d4d00)
	/Users/ccummer/go/src/github.com/wtfutil/wtf/app/wtf_app.go:107 +0x8c
github.com/rivo/tview.(*Application).Run(0xc0005d4d00, 0x0, 0x0)
	/Users/ccummer/go/pkg/mod/github.com/rivo/tview@v0.0.0-20190829161255-f8bc69b90341/application.go:219 +0x486
main.main()
	/Users/ccummer/go/src/github.com/wtfutil/wtf/main.go:73 +0x37e
```

wtfutil version 0.24
Ubuntu 18.04.3 LTS

Is there some additional config I missed that isn't listed on the docker module page?

**Comment by PartyLich** [comment]
Worked after restarting the application. To clarify, I had updated my config while wtfutil was running, which had worked without issue for all of the other modules I've tried. My issue seems to be resolved, but if there's some other info I can provide to track down this weird case, let me know. Happy to help.
